// Real Paperboy Ventures blog posts, imported from the Squarespace site
// (paperboyventures.com/blog) via its ?format=json API. Images are
// self-hosted under public/press/<slug>/. Regenerate with the import
// script (see plan) rather than editing bodies by hand. Imported 2026-07-13.

export type PressSpan = { text: string; href?: string };
export type PressBlock =
  | { type: "h"; text: string }
  | { type: "p"; spans: PressSpan[] }
  | { type: "quote"; text: string }
  | { type: "img"; src: string; alt?: string };

export type PressPost = {
  slug: string;
  sourceUrl: string;
  title: string;
  tag?: string; // e.g. "DEALS · Ep. 25"
  date: string; // ISO yyyy-mm-dd
  author: string;
  excerpt: string;
  heroImage: string;
  blocks: PressBlock[];
  youtube?: string;
  spotify?: string;
};

// A/B thumbnail treatments (Higgsfield-generated, typeset with the DEALS chrome).
// Posts listed here render TWO cards on /press — one per direction — for
// side-by-side review; both cards link to the same article. Collapse to a
// single entry once a direction wins.
export const PRESS_THUMBNAILS: Record<string, { a: string; b: string }> = {
  toto: { a: "/press/toto/thumb-a.jpg", b: "/press/toto/thumb-b.jpg" },
  cheddies: { a: "/press/cheddies/thumb-a.jpg", b: "/press/cheddies/thumb-b.jpg" },
  "cpg-investor-guide": {
    a: "/press/cpg-investor-guide/thumb-a.jpg",
    b: "/press/cpg-investor-guide/thumb-b.jpg",
  },
};

// Newest first.
export const PRESS_POSTS: PressPost[] = [
  {
    slug: "cpg-investor-guide",
    sourceUrl: "https://www.paperboyventures.com/blog/cpginvestorguide",
    title: "CPG Investor Guide",
    date: "2026-03-10",
    author: "Kyle Fitzpatrick",
    excerpt: "A comprehensive list of VCs, Angel Groups, and Family Offices investing in consumer goods (US).",
    heroImage: "/press/cpg-investor-guide/hero.png",
    blocks: [
      { type: "img", src: "/press/cpg-investor-guide/body-1.png" },
      { type: "p", spans: [{ text: "Access the full list here", href: "https://docs.google.com/spreadsheets/d/1ngd4d6b4YlaRhexM6CW1mNtCMH39ROBxkmc13ZZiI_g/edit?usp=sharing" }] },
      { type: "h", text: "Do’s & Dont’s for Making This List Work" },
      { type: "p", spans: [{ text: "DO — Start local. Investors in your geographical vicinity are more likely to take a meeting. Leverage the power of proximity." }] },
      { type: "p", spans: [{ text: "DON’T — Mass message the whole list. Targeted outreach > spray-and-pray." }] },
      { type: "p", spans: [{ text: "DO — Take time to research groups that show interest in your specific category. Personalize accordingly." }] },
      { type: "p", spans: [{ text: "DON’T — Overload your intro message. Pique interest first, then go deeper once they engage." }] },
      { type: "p", spans: [{ text: "DO — Keep your cold pitch extremely short. Three lines max for email, two lines for LinkedIn. Short messages win at a much higher rate." }] },
      { type: "p", spans: [{ text: "DON’T — Expect responses from everyone. Even a 10% reply rate can be a win. All it takes is one…" }] },
      { type: "p", spans: [{ text: "DO — Offer to send product samples to interested investors. It’s expensive but getting product into investor homes is a great way to earn mindshare and build a relationships." }] },
      { type: "p", spans: [{ text: "DON’T — Ask for a call “just to connect”. Be mindful that investors have many people asking for their time. Only suggest a call once interest is established on their end." }] },
      { type: "p", spans: [{ text: "DO — Be clear about what you’re raising (amount, general terms, timeline). Ambiguity is never a good sign in raising $." }] },
    ],
  },
  {
    slug: "toto",
    sourceUrl: "https://www.paperboyventures.com/blog/toto",
    title: "Toto",
    tag: "DEALS · Ep. 25",
    date: "2025-06-23",
    author: "Kyle Fitzpatrick",
    excerpt: "Soft-baked cookies with clean, whole food ingredients.",
    heroImage: "/press/toto/hero.jpg",
    blocks: [
      { type: "h", text: "A chat with Toto CEO, Sydney Webb" },
      { type: "img", src: "/press/toto/body-1.jpg" },
      { type: "p", spans: [{ text: "Catch the interview on " }, { text: "Youtube", href: "https://youtu.be/9M6t4sPsYco" }, { text: " or " }, { text: "Spotify", href: "https://open.spotify.com/episode/5HOPvv3S37yzdYa8gWVrWY?si=tyaOyT6xRjKBL4LCOZl3bw" }, { text: ". Subscribe to " }, { text: "DEALS here", href: "/deals" }, { text: "." }] },
      { type: "h", text: "What Stands Out" },
      { type: "p", spans: [{ text: "Soft-baked cookies made clean." }] },
      { type: "p", spans: [{ text: "Toto cookies taste like the Toll House ones you grew up with, but without the poor ingredients. No seed oils, refined sugars, gluten, or dairy." }] },
      { type: "p", spans: [{ text: "Just real, whole food ingredients that treat the body well." }] },
      { type: "p", spans: [{ text: "The brand has grown fast, now in +4k stores. Impressively, Toto has done so with zero paid ads and millions of organic impressions powered by word-of-mouth and a deeply loyal fanbase." }] },
      { type: "p", spans: [{ text: "Founder Sydney Webb created Toto after a decade-long health journey that included Crohn’s disease and early-stage colon cancer. She started baking in her parents’ kitchen with a simple goal: rebuild comfort food from scratch." }] },
      { type: "p", spans: [{ text: "“We wanted to recreate the feeling of indulgence without the crash. Something that actually supported your health.” - Sydney" }] },
      { type: "h", text: "A World of Unhealthy Cookies" },
      { type: "p", spans: [{ text: "Most packaged cookies still fall short, even in the natural set. Seed oils, refined sugars, and unrecognizable ingredients are common. Labels might say \"clean,\" but the ingredient lists tell a different story." }] },
      { type: "p", spans: [{ text: "Sydney experienced this firsthand. For years, she struggled to find snacks that worked for her gut and still delivered on taste. She wasn’t looking for diet food. She wanted something nostalgic and satisfying that didn’t leave her feeling worse afterward." }] },
      { type: "p", spans: [{ text: "“I didn’t want another low-fat snack pretending to be clean. I wanted something real that tasted amazing and made me feel good.” - Sydney" }] },
      { type: "p", spans: [{ text: "Toto was created to fill that gap. A true comfort food made with intention." }] },
      { type: "img", src: "/press/toto/body-2.jpeg" },
      { type: "p", spans: [{ text: "Sea Salt and Chocolate Chip Cookies by Toto" }] },
      { type: "h", text: "Toto’s Approach to Better Cookies" },
      { type: "p", spans: [{ text: "Toto’s cookies are indulgent, functional, and built with real ingredients. Each one delivers 8 to 10 grams of organic plant protein and contains no seed oils, gluten, dairy, preservatives, or refined sugar." }] },
      { type: "p", spans: [{ text: "The lineup includes:" }] },
      { type: "p", spans: [{ text: "Peanut Butter Chocolate Chip" }] },
      { type: "p", spans: [{ text: "Sea Salt Chocolate Chip" }] },
      { type: "p", spans: [{ text: "Cinnamon Roll" }] },
      { type: "p", spans: [{ text: "S’mores" }] },
      { type: "p", spans: [{ text: "Double Chocolate Chip" }] },
      { type: "p", spans: [{ text: "Birthday Cake" }] },
      { type: "p", spans: [{ text: "Toto launched online and took off quickly through pure community pull. There were no ads or paid influencers. Sydney still blocks off time every day to personally respond to customer DMs with voice notes. That one-on-one connection has built a devoted following that drives trial, repeat orders, and organic content." }] },
      { type: "p", spans: [{ text: "Retail has followed a similar path. Cinnamon Roll launched as a limited-time SKU at Sprouts and sold out immediately. It is now part of the permanent set. Toto is now stocked at Central Market, Fresh Thyme, and Vitamin Shoppe, with Costco and 7-Eleven tests launching soon." }] },
      { type: "p", spans: [{ text: "“We built community first. That’s what scaled the brand.” - Sydney" }] },
      { type: "img", src: "/press/toto/body-3.png" },
      { type: "p", spans: [{ text: "CEO Sydney Webb" }] },
      { type: "h", text: "The Future is Soft-Baked" },
      { type: "p", spans: [{ text: "Toto is on track to triple revenue this year by focusing on depth, not just distribution. The strategy is simple: increase velocity at top-performing accounts, use the data to unlock national retailers, and expand carefully." }] },
      { type: "p", spans: [{ text: "A second product line is coming in 2026. It will still live in the cookie set but introduce a new format that blends functional nutrition with nostalgic flavor. More innovations are on deck, all following the same philosophy: clean, delicious, and comfort-first." }] },
      { type: "p", spans: [{ text: "The team is lean and growing. Toto currently has two full-time employees and a trusted network of advisors and contractors. Key hires are planned in operations, marketing, and sales." }] },
      { type: "p", spans: [{ text: "Sydney’s long-term vision includes more than product. She plans to launch a give-back program focused on food literacy and self-worth for young women. The idea is to build something like a wellness scouts program for the next generation." }] },
      { type: "p", spans: [{ text: "“We’re not just selling cookies. We’re helping people feel good in their bodies and building a brand that reflects that.” - Sydney" }] },
    ],
    youtube: "https://youtu.be/9M6t4sPsYco",
    spotify: "https://open.spotify.com/episode/5HOPvv3S37yzdYa8gWVrWY?si=tyaOyT6xRjKBL4LCOZl3bw",
  },
  {
    slug: "cheddies",
    sourceUrl: "https://www.paperboyventures.com/blog/cheddies",
    title: "Cheddies",
    tag: "DEALS · Ep. 24",
    date: "2025-06-03",
    author: "Kyle Fitzpatrick",
    excerpt: "Crispy cheese crackers made with organic cheddar.",
    heroImage: "/press/cheddies/hero.jpg",
    blocks: [
      { type: "h", text: "A chat with Team Cheddies: Anish Seth (CEO), Tomas Pergola (co/f), & Francisco Pergola (co/f)" },
      { type: "img", src: "/press/cheddies/body-1.png" },
      { type: "p", spans: [{ text: "Catch the interview on " }, { text: "Youtube", href: "https://youtu.be/l-DswW0bCXs" }, { text: " or " }, { text: "Spotify", href: "https://creators.spotify.com/pod/dashboard/episodes" }, { text: ". Subscribe to " }, { text: "DEALS here", href: "/deals" }, { text: "." }] },
      { type: "h", text: "What Stands Out" },
      { type: "p", spans: [{ text: "Crispy cheese crackers made with organic cheddar." }] },
      { type: "p", spans: [{ text: "Cheddies is shaking up the $8b (US) cheese cracker aisle with real cheese, minimal processing, and a BFY ingredient profile that delivers on flavor." }] },
      { type: "p", spans: [{ text: "Real, aged cheddar > processed cheese powders." }] },
      { type: "p", spans: [{ text: "“It started in our kitchen. We’d grind cheddar right into the dough by hand, batch by batch. It’s a hard product to make, but the quality gives us an edge. - Tomas" }] },
      { type: "h", text: "A Legacy Category" },
      { type: "p", spans: [{ text: "Cheese crackers is an enormous and outdated product category." }] },
      { type: "p", spans: [{ text: "The vast majority of these crackers on US shelves today are made with ultra-processed cheese powders, not real cheese." }] },
      { type: "p", spans: [{ text: "Despite that, the market is lucrative." }] },
      { type: "p", spans: [{ text: "Cheez-It and Goldfish lead the way, each driving over +$1b in annual revenue. Annie’s comes third in the $4-500m range." }] },
      { type: "p", spans: [{ text: "The sub-set of premium snack crackers is growing well (+16% YoY per " }, { text: "SPINS", href: "https://www.spins.com/" }, { text: ") with strong M&A potential as shown by the $795m Simple Mills " }, { text: "acquisition", href: "https://www.prnewswire.com/news-releases/flowers-foods-inc-completes-acquisition-of-simple-mills-302382314.html" }, { text: " in February." }] },
      { type: "p", spans: [{ text: "“There’s a void between Annie’s and Cheez-It. We built Cheddies to fill it - with real cheese, real ingredients, and a responsible brand.” - Anish." }] },
      { type: "img", src: "/press/cheddies/body-2.jpg" },
      { type: "p", spans: [{ text: "Cheddies Spicy Chili Lime Cheese Crackers" }] },
      { type: "h", text: "The Cheddies Approach" },
      { type: "p", spans: [{ text: "Cheddies bakes cheese directly into the crackers rather than dusting them post-bake, resulting in 4x more cheese, richer taste, and higher protein." }] },
      { type: "p", spans: [{ text: "No artificial colors, preservatives, or dyes." }] },
      { type: "p", spans: [{ text: "The light and airy crackers come in four cheddar-forward varieties:" }] },
      { type: "p", spans: [{ text: "🧀 Classic🧀 🧀 Double🔥 Spicy🌶 Chili Lime" }] },
      { type: "p", spans: [{ text: "Supply chain transparency is a core value of the brand which works directly with " }, { text: "regenerative farms", href: "https://alexandrefamilyfarm.com/" }, { text: " to source the highest quality dairy possible." }] },
      { type: "p", spans: [{ text: "Better for the product. Better for the planet." }] },
      { type: "p", spans: [{ text: "“We’re not here to slap ‘natural’ on a box and call it innovation. This is a fundamentally different approach to how cheese crackers are made.” — Tomas." }] },
      { type: "img", src: "/press/cheddies/body-3.jpg" },
      { type: "p", spans: [{ text: "Cheddies Spicy Cheddar Cheese Crackers" }] },
      { type: "h", text: "Building a Cheddar Tomorrow" },
      { type: "p", spans: [{ text: "The brand is rapidly gaining ground…" }] },
      { type: "p", spans: [{ text: "Strong velocities at Whole Foods and Sprouts have made Cheddies one of the fastest-growing cracker brands in the Natural channel." }] },
      { type: "p", spans: [{ text: "Club pilots kick-off this summer with rotations scheduled at Costco (Pacific NW) and BJ’s (Mid-Atlantic) in June and July." }] },
      { type: "p", spans: [{ text: "This Fall, Cheddies launches an exclusive new pizza flavor in collaboration with Steve Aoki, available only at Whole Foods." }] },
      { type: "p", spans: [{ text: "7-Eleven is onboard as a retail partner and strategic investor (via " }, { text: "7-Ventures", href: "https://7-ventures.co/" }, { text: ")." }] },
      { type: "p", spans: [{ text: "More doors. More placements. More cheese." }] },
      { type: "p", spans: [{ text: "“We built Cheddies to be the brand families grow up with. The one kids shout for, and parents actually feel good about buying. If we stay true to real ingredients and real values, there’s no ceiling to what we can build” - Francisco" }] },
    ],
    youtube: "https://youtu.be/l-DswW0bCXs",
  },
  {
    slug: "hemp-thc-beverages",
    sourceUrl: "https://www.paperboyventures.com/blog/hemp-thc-bev",
    title: "The Wild World of Hemp-Derived THC Beverages",
    date: "2025-06-02",
    author: "Kyle Fitzpatrick",
    excerpt: "An insiders perspective on the state of the industry with Jake Bullock (CEO, Cann) and Diana Eberlein (CEAO, Vertosa).",
    heroImage: "/press/hemp-thc-beverages/hero.png",
    blocks: [
      { type: "h", text: "A chat with Jake Bullock (Cann) and Diana Eberlein (Vertosa)" },
      { type: "img", src: "/press/hemp-thc-beverages/body-1.png" },
      { type: "p", spans: [{ text: "Catch the interview with " }, { text: "Jake", href: "https://www.linkedin.com/in/jakebullock/" }, { text: " & " }, { text: "Diana", href: "https://www.linkedin.com/in/diana-eberlein/" }, { text: " on " }, { text: "Youtube", href: "https://youtu.be/garc2ZyiHD4" }, { text: " or " }, { text: "Spotify.", href: "https://open.spotify.com/show/7dLSJEJWuN0PQOX6bOddUz" }] },
      { type: "h", text: "State of the Market" },
      { type: "p", spans: [{ text: "Hemp-derived THC beverages are surging in the US despite a complicated and contradictory regulatory environment." }] },
      { type: "p", spans: [{ text: "Sales of the white-hot segment hit $382m in 2024 (+275% vs. 2023) and are projected to " }, { text: "10x to $4.1b", href: "https://www.euromonitor.com/article/fizz-with-a-buzz-the-rise-of-cannabis-drinks-in-the-us" }, { text: " (US) in the next four years." }] },
      { type: "p", spans: [{ text: "All at a time of immense uncertainty as questions loom over how state and federal lawmakers will move forward." }] },
      { type: "p", spans: [{ text: "Texas just passed SB3, essentially banning THC beverages from the state. That bill is now sitting on Gov. Abbott’s desk for signature." }] },
      { type: "p", spans: [{ text: "On the federal level, the Farm Bill is up for renewal later this year. It’s anybody’s guess which way that’ll go." }] },
      { type: "p", spans: [{ text: "“This category is growing faster than the laws can keep up, but the direction is clear. Consumers want this, and the market is responding.” - Jake" }] },
      { type: "h", text: "The Loophole —> 2018 Farm Bill" },
      { type: "p", spans: [{ text: "The 2018 Farm Bill unintentionally created a loophole by legalizing hemp with less than 0.3% Delta-9 THC, opening the door for intoxicating compounds to be extracted and sold in consumer products." }] },
      { type: "p", spans: [{ text: "The original intent was to legalize industrial hemp for agricultural and commercial use, mainly for fiber and grain. Lawmakers didn’t anticipate that manufacturers would extract intoxicating THC compounds from hemp." }] },
      { type: "p", spans: [{ text: "But the proverbial cat is out of the bag…" }] },
      { type: "p", spans: [{ text: "THC drinks have exploded over the past few years by way of partnerships with major retailers and distributors across the US." }] },
      { type: "p", spans: [{ text: "Often marketed as alternatives to alcohol, traction is building with consumers looking for a different kind of buzz:" }] },
      { type: "p", spans: [{ text: "“It’s replacing two glasses of wine on a Tuesday. That’s the moment we’re winning. Those quiet, end-of-day rituals where people want to feel good but stay sharp.” - Diana" }] },
      { type: "img", src: "/press/hemp-thc-beverages/body-2.png" },
      { type: "p", spans: [{ text: "Texas Tribune article, May 25 2025." }] },
      { type: "h", text: "Federal vs. State Regulations" },
      { type: "p", spans: [{ text: "The next Farm Bill isn’t expected to pass until late 2025 / 2026, leaving states to navigate the regulatory landscape independently." }] },
      { type: "p", spans: [{ text: "This has resulted in a patchwork of laws governing hemp-derived THC beverages, with the majority of states establishing regulatory frameworks and others going the route of bans." }] },
      { type: "p", spans: [{ text: "\"Sixteen states considered bans on hemp-derived THC products this year, and fifteen of those efforts failed. Texas is the outlier.\" - Jake" }] },
      { type: "p", spans: [{ text: "Well, Texas and California." }] },
      { type: "p", spans: [{ text: "California enacted an emergency ban in September 2024, citing concerns over sales to minors. The ban prohibits any detectable amount of THC in hemp-derived food, beverages, and dietary supplements." }] },
      { type: "p", spans: [{ text: "The results have been mixed with challenges enforcing these rules in unlicensed venues and online marketplaces." }] },
      { type: "p", spans: [{ text: "“In California, 70% of the market went illicit after the ban. The legal products disappeared, but the high-potency synthetics stayed on shelves in head shops and smoke shops. There’s no tax base left to fund enforcement, and the illicit market thrives.” - Diana" }] },
      { type: "p", spans: [{ text: "Texas is now on a path to follow suit." }] },
      { type: "p", spans: [{ text: "Meanwhile, hemp industry advocates are pushing for clear standards in place of bans." }] },
      { type: "h", text: "A Framework for Sensible Regulation" },
      { type: "p", spans: [{ text: "\"We're not fighting regulation. We're asking for it. Tax us. Test us. Treat us like alcohol.\" - Jake." }] },
      { type: "p", spans: [{ text: "The most widely endorsed framework for regulation includes the following guardrails:" }] },
      { type: "p", spans: [{ text: "(1) Dosage" }] },
      { type: "p", spans: [{ text: "Enforce limits per serving (10mg) and per package (100mg)." }] },
      { type: "p", spans: [{ text: "(2) Third-Party Testing" }] },
      { type: "p", spans: [{ text: "Lab testing for THC content as well as pesticides, heavy metals, and synthetic byproducts." }] },
      { type: "p", spans: [{ text: "(3) Labeling" }] },
      { type: "p", spans: [{ text: "Clear communication of THC content as well as usage warnings and QR codes linking to lab results." }] },
      { type: "p", spans: [{ text: "(4) Age Gating" }] },
      { type: "p", spans: [{ text: "21+ ID checks at all points of sale to enforce adults-only access." }] },
      { type: "p", spans: [{ text: "(5) Distribution" }] },
      { type: "p", spans: [{ text: "Modeled after alcohol, a license-based retail system that’d give states control over where and how THC beverages are sold, helping ensure products reach consumers through vetted, compliant channels." }] },
    ],
    youtube: "https://youtu.be/garc2ZyiHD4",
    spotify: "https://open.spotify.com/show/7dLSJEJWuN0PQOX6bOddUz",
  },
  {
    slug: "just-date",
    sourceUrl: "https://www.paperboyventures.com/blog/justdate",
    title: "Just Date",
    tag: "DEALS · Ep. 23",
    date: "2025-05-21",
    author: "Kyle Fitzpatrick",
    excerpt: "A better-for-you approach to the sugar aisle.",
    heroImage: "/press/just-date/hero.png",
    blocks: [
      { type: "h", text: "A chat with Samantha Abramson, CEO of Just Date" },
      { type: "img", src: "/press/just-date/body-1.png" },
      { type: "p", spans: [{ text: "Catch the interview on " }, { text: "Youtube", href: "https://youtu.be/VmGZrigQMP4" }, { text: " or " }, { text: "Spotify", href: "https://open.spotify.com/show/7dLSJEJWuN0PQOX6bOddUz" }, { text: ". Subscribe to " }, { text: "DEALS here", href: "/deals" }, { text: "." }] },
      { type: "h", text: "What Stands Out" },
      { type: "p", spans: [{ text: "A better-for-you approach to the sugar aisle." }] },
      { type: "p", spans: [{ text: "Just Date harnesses the natural sweetness of Medjool dates to craft sweets without the sugar spike." }] },
      { type: "p", spans: [{ text: "The breakthrough products:" }] },
      { type: "p", spans: [{ text: "🍫Dark chocolate chips🥛Milk chocolate chips" }] },
      { type: "p", spans: [{ text: "These are the first-ever date-sweetened chocolate chips on the market, delivering 50% less sugar vs. conventional chips - plus added fiber, antioxidants, potassium, and magnesium." }] },
      { type: "p", spans: [{ text: "“We stick to one sweetener: dates. Because they come with fiber, antioxidants, and minerals. Not just empty calories.” - Sam Abramson." }] },
      { type: "h", text: "The Sugar Problem" },
      { type: "p", spans: [{ text: "Americans consume an average of 17 teaspoons of added sugar per day, far more than the American Heart Association’s reccomended limit of six teaspoons for women and nine for men." }] },
      { type: "p", spans: [{ text: "This has influenced a growing public health crisis with 133 million US adults living with diabetes / prediabetes, 77% of whom are actively trying to reduce sugar intake." }] },
      { type: "p", spans: [{ text: "Refined sugar hides in plain sight in many of our foods today, from breads to sauces, yogurts to protein bars, and all things in between." }] },
      { type: "p", spans: [{ text: "The long-term effects of heightened sugar intake include metabolic dysfunction, weight gain, chronic inflammation, and insulin resistance." }] },
      { type: "p", spans: [{ text: "Consumers are waking up and searching for something better." }] },
      { type: "img", src: "/press/just-date/body-2.jpg" },
      { type: "p", spans: [{ text: "Just Date product lineup. Chocolate chips, syrups, and sugar." }] },
      { type: "h", text: "The Just Date Solution" },
      { type: "p", spans: [{ text: "Just Date offers a clean, modern alternative to conventional sugar with a product line that includes chocolate chips, syrups, and granulated sugar." }] },
      { type: "p", spans: [{ text: "Each product follows a strict clean-label, low-glycemic formula made with five or fewer organic ingredients, clinically tested to avoid blood sugar spikes." }] },
      { type: "p", spans: [{ text: "“The mission has always been simple ingredients that don’t spike your blood sugar, and they have to taste amazing.” - Sam Abramson" }] },
      { type: "p", spans: [{ text: "The brand’s foundation is Medjool dates, which bring not only natural sweetness but also potassium, magnesium, fiber, and antioxidants." }] },
      { type: "p", spans: [{ text: "Just Date was founded by Dr. Sylvie Charles, a physician who saw firsthand the damage sugar was doing to her patients’ health. CEO Samantha Abramson leads day-to-day operations with deep expertise in brand building and marketing strategy." }] },
      { type: "p", spans: [{ text: "More than just a chocolate chip, this could be the start of a category-defining platform." }] },
      { type: "img", src: "/press/just-date/body-3.jpg" },
      { type: "h", text: "Future Potential" },
      { type: "p", spans: [{ text: "Just Date is strongly positioned to go far beyond baking." }] },
      { type: "p", spans: [{ text: "The brand is building meaningful traction at key retailers like Whole Foods, Sprouts, and Kroger, proving that date-sweetened products resonate with everyday shoppers." }] },
      { type: "p", spans: [{ text: "Beyond retail, the opportunities in foodservice and B2B ingredient supply are equally as compelling and lucrative." }] },
      { type: "p", spans: [{ text: "Combining these opportunities the addressable market is well into the 9-figures." }] },
      { type: "p", spans: [{ text: "“We’re continuing to grow date sweetening… and the more awareness grows, the more opportunity there is to lead. We’ve been doing this since 2018.” — Sam Abramson" }] },
    ],
    youtube: "https://youtu.be/VmGZrigQMP4",
    spotify: "https://open.spotify.com/show/7dLSJEJWuN0PQOX6bOddUz",
  },
  {
    slug: "startup-cpg-valuations",
    sourceUrl: "https://www.paperboyventures.com/blog/dan-habitat",
    title: "Startup CPG Valuations",
    date: "2025-05-14",
    author: "Kyle Fitzpatrick",
    excerpt: "A chat with Daniel Faierman of Habitat Partners. Investor in Popup Bagels, Mezcla, Ayoh Foods, + more.",
    heroImage: "/press/startup-cpg-valuations/hero.png",
    blocks: [
      { type: "h", text: "A chat with Daniel Faierman of Habitat Partners" },
      { type: "img", src: "/press/startup-cpg-valuations/body-1.png" },
      { type: "p", spans: [{ text: "Catch the interview on " }, { text: "Youtube", href: "https://youtu.be/MABudihVon8" }, { text: " or " }, { text: "Spotify", href: "https://open.spotify.com/show/7dLSJEJWuN0PQOX6bOddUz" }, { text: ". Subscribe to Dan’s newsletter “" }, { text: "Term Sheet Pitfalls", href: "https://termsheetpitfalls.beehiiv.com/" }, { text: "”." }] },
      { type: "h", text: "Art > Science" },
      { type: "p", spans: [{ text: "The single biggest disconnect in early-stage CPG fundraising:" }] },
      { type: "p", spans: [{ text: "👉 Valuations" }] },
      { type: "p", spans: [{ text: "We’ve seen hundreds of pitches in the past 18 months and the gap between what founders think their business is worth and what investors are willing to pay has never been more pronounced." }] },
      { type: "p", spans: [{ text: "Why the misalignment?" }] },
      { type: "p", spans: [{ text: "Mainly b/c the valuation metrics that apply to a $20m brand simply don’t translate to one doing $2m in revenue." }] },
      { type: "p", spans: [{ text: "Metrics like EBITDA/revenue multiples and tools like DCFs are essentially useless in seed funding." }] },
      { type: "p", spans: [{ text: "“Valuing early-stage CPG brands is far more art than science. You’re making judgement calls and there’s just not enough data to plug into a model. So instead, you’re pattern-matching, drawing from past experience, and trying to find signal in a messy picture.” - Dan" }] },
      { type: "p", spans: [{ text: "At this stage, valuation is much more about triangulation vs. calculation." }] },
      { type: "p", spans: [{ text: "So what factors matter most in this process?" }] },
      { type: "h", text: "Five Key Drivers" },
      { type: "p", spans: [{ text: "1. Founding Team Experience2. All-in Gross Margin3. Proof of Retail Velocity 4. Brand Addressable Market5. Exit Potential" }] },
      { type: "img", src: "/press/startup-cpg-valuations/body-2.png" },
      { type: "p", spans: [{ text: "Habitat portfolio company, " }, { text: "Pop-up Bagels", href: "https://www.restaurantbusinessonline.com/emerging-brands/popup-bagels-launches-franchising-new-funding-round" }] },
      { type: "h", text: "Founding Team Experience" },
      { type: "p", spans: [{ text: "With limited metrics at play the experience level of the founding team becomes the clearest indicator of future performance. Investors are drawn to founders who’ve either built something before or have deep functional experience in the relevant category:" }] },
      { type: "p", spans: [{ text: "“There’s a ton of fragmentation in early-stage CPG. It’s easy to get excited by a cool brand, but we’re looking for founders with real operating range. That could be deep supply chain knowledge, or a clear command of brand strategy. Ideally both.” - Dan" }] },
      { type: "p", spans: [{ text: "Second-time founders and operators from breakout brands get more credit, especially if they understand the gritty realities of scaling: margin management, channel conflict, co-man challenges, capital efficiency, etc." }] },
      { type: "p", spans: [{ text: "On the other hand, first-time founders without category fluency often struggle to justify higher valuations or secure institutional backing." }] },
      { type: "h", text: "All-In Gross Margin" },
      { type: "p", spans: [{ text: "Few numbers tell investors more about a brand’s viability than its All-In gross margin." }] },
      { type: "p", spans: [{ text: "All-in margin = product (COGS) + freight, fulfillment, and warehousing. If that number is flawed, everything downstream becomes harder to scale:" }] },
      { type: "p", spans: [{ text: "“If your gross margins are broken, nothing else really matters. You can’t fix them easily without changing the product. And strategics won’t want to either.” - Dan." }] },
      { type: "p", spans: [{ text: "Target ranges vary drastically by category. For packaged food, 30-35% is viable. For beauty and body care it should be closer to 60%." }] },
      { type: "p", spans: [{ text: "These margins aren’t just about profitability down the line. They determine how much a brand can invest in trade spend, marketing, and headcount today without burning unsustainable amounts of cash." }] },
      { type: "img", src: "/press/startup-cpg-valuations/body-3.png" },
      { type: "p", spans: [{ text: "Habitat portfolio company, " }, { text: "Mezcla", href: "https://www.foodbusinessnews.net/articles/25403-mezcla-raises-4-million-in-series-a-round" }] },
      { type: "h", text: "Retail Velocity" },
      { type: "p", spans: [{ text: "While getting on-shelf is a milestone worth celebrating, velocity tells the real story." }] },
      { type: "p", spans: [{ text: "Investors are less interested in how many stores a brand is in and more focused on how it performs in each one." }] },
      { type: "p", spans: [{ text: "“Retail velocity is the proof point we care about most. You don’t need to be in 5,000 doors—but if you’re doing double-digit units per store per week in a respected retailer, that tells us a lot.” - Dan." }] },
      { type: "p", spans: [{ text: "High velocity in limited doors signals real consumer demand with scale potential. It shows the brand can drive repeat purchases without relying entirely on outsized promo budgets." }] },
      { type: "h", text: "Brand Addressable Market" },
      { type: "p", spans: [{ text: "Category size is a starting point, but what matters most is how much of it a brand can realistically own. This goes beyond broad TAM and focuses on brand-specific addressability." }] },
      { type: "p", spans: [{ text: "That means understanding target consumers, price positioning, and how the product fits into existing shopper habits." }] },
      { type: "p", spans: [{ text: "“We look at whether this brand can carve out a sizable piece of a real market,” Dan explained. “That means right format, right price, right timing. We're not just betting on the category, we're betting on how much of it this team can win.” - Dan." }] },
      { type: "p", spans: [{ text: "Investors want to see founders who have thought critically about where they fit and how big their slice can be. The best pitches go beyond market theory and make a compelling case for real-world share." }] },
      { type: "img", src: "/press/startup-cpg-valuations/body-4.jpg" },
      { type: "p", spans: [{ text: "Habitat portfolio company, " }, { text: "Ayoh Mayo", href: "https://businessden.com/2025/03/13/creative-mayo-maker-raises-4-5m-in-bid-to-be-household-condiment-name/" }] },
      { type: "h", text: "Exit Potential" },
      { type: "p", spans: [{ text: "Every early-stage investment is ultimately an exit bet." }] },
      { type: "p", spans: [{ text: "It’s not just about growth, but who might buy it, why, and when." }] },
      { type: "p", spans: [{ text: "This means thinking through detailed acquisition scenarios based on all factors listed above." }] },
      { type: "p", spans: [{ text: "“If a big CPG player can’t materially improve your margin or scale your distribution, they’re probably not buying you.” - Dan." }] },
      { type: "p", spans: [{ text: "At the seed stage, that lens heavily influences valuation. If the only way to justify a high price is to assume multiple massive capital raises and long-term dilution, it's likely not a fit." }] },
      { type: "p", spans: [{ text: "Investors want to see a believable pathway to acquisition, not just a theoretical one." }] },
    ],
    youtube: "https://youtu.be/MABudihVon8",
    spotify: "https://open.spotify.com/show/7dLSJEJWuN0PQOX6bOddUz",
  },
  {
    slug: "flowerboy",
    sourceUrl: "https://www.paperboyventures.com/blog/seatopia-3nz2p-cychb",
    title: "Flowerboy",
    tag: "DEALS · Ep. 22",
    date: "2025-05-08",
    author: "Kyle Fitzpatrick",
    excerpt: "THC-infused social sodas with functional benefits and nostalgic flavors.",
    heroImage: "/press/flowerboy/hero.png",
    blocks: [
      { type: "h", text: "A chat with Kyle Cooke, Founder & CEO" },
      { type: "img", src: "/press/flowerboy/body-1.png" },
      { type: "p", spans: [{ text: "Catch the interview on " }, { text: "Youtube", href: "https://youtu.be/V6uTFVXujOE" }, { text: " or " }, { text: "Spotify", href: "https://open.spotify.com/show/7dLSJEJWuN0PQOX6bOddUz" }, { text: ". Subscribe to " }, { text: "DEALS here", href: "/deals" }, { text: "." }] },
      { type: "h", text: "What Stands Out" },
      { type: "p", spans: [{ text: "A nostalgic approach to the cannabis beverage category…" }] },
      { type: "p", spans: [{ text: "Flowerboy makes THC-infused social sodas with throwback flavors designed for modern consumers." }] },
      { type: "p", spans: [{ text: "Each soda is infused with 5mg of hemp-derived Delta-9 THC plus a blend of adaptogens and nootropics for a balanced cannabis experience." }] },
      { type: "p", spans: [{ text: "Reality TV-star and 2x beverage entrepreneur Kyle Cooke leads the brand, bringing a built-in audience, national visibility, and a proven distribution playbook to the table." }] },
      { type: "p", spans: [{ text: "“You drink a Flowerboy and you’re not on the couch zonked out—you’re in the mix, you’re sharp, you’re chatty. It’s a different type of THC experience, and I think it’s what the broader market actually wants.” - Kyle" }] },
      { type: "h", text: "The Market: Hemp-Derived THC Bevs" },
      { type: "p", spans: [{ text: "Relative to the US alcohol market ($250b), hemp-derived THC beverages are a blip on the radar ($382m), but that’s changing quickly." }] },
      { type: "p", spans: [{ text: "The category is projected to " }, { text: "10x to $4.1b", href: "https://engage.squarespace-mail.com/r?m=6818bda70960e50fb6e5eac5&u=https%3A%2F%2Fwww.euromonitor.com%2Farticle%2Ffizz-with-a-buzz-the-rise-of-cannabis-drinks-in-the-us&w=6585e7cf9929135ae34643f2&c=b_6814d29ba8d4486d388df519&l=en-US&s=xRbpKpIeG3VK7U7DBiCDd4ahDVk%3D" }, { text: " over the next four years, fueled by a consumer shift towards buzz-without-booze alternatives." }] },
      { type: "p", spans: [{ text: "The regulatory backdrop remains complex." }] },
      { type: "p", spans: [{ text: "Federal and state laws still contradict one another, and regulations in states like " }, { text: "California", href: "https://mjbizdaily.com/california-extends-hemp-derived-thc-ban/" }, { text: " and " }, { text: "Texas", href: "https://www.texastribune.org/2025/05/01/thc-hemp-regulations-senate-bill-3-texas-house/" }, { text: " reflect the ongoing tension between consumer demand and legislative control." }] },
      { type: "p", spans: [{ text: "But brands willing to navigate the market friction could be in line for outsized returns…" }] },
      { type: "img", src: "/press/flowerboy/body-2.png" },
      { type: "p", spans: [{ text: "Flowerboy product lineup. Classic Cola, Grape, and Orange." }] },
      { type: "h", text: "The Flowerboy Approach" },
      { type: "p", spans: [{ text: "Flowerboy launched in December 2024 with three SKUs:" }] },
      { type: "p", spans: [{ text: "🥤 Classic Cola🍇 Grape Soda🍊 Orange Soda" }] },
      { type: "p", spans: [{ text: "Each with 5g of sugar or less, Flowerboy drinks like a full-flavored soda but functions like a modern alcohol alternative. Ideal for social settings like concerts, parties, and nights out." }] },
      { type: "p", spans: [{ text: "Nootropics = Lion’s mane, B12, caffeineAdaptogens = Cordyceps, L-theanine, ginseng" }] },
      { type: "p", spans: [{ text: "All to deliver a calming, energetic consumption experience." }] },
      { type: "p", spans: [{ text: "And thanks to Loverboy’s established wholesale and retail infrastructure, Flowerboy is well-positioned to scale distribution quickly and efficiently." }] },
      { type: "p", spans: [{ text: "“We’re now talking to our top wholesalers and retail partners from Loverboy to bring in Flowerboy, which has always been the game plan. DTC was just our launchpad. But 98% of adult beverages are still bought at retail.” - Kyle" }] },
      { type: "p", spans: [{ text: "Flowerboy will also benefit from Kyle’s media presence (including Bravo’s Summer House) to drive top-of-funnel awareness and build cultural momentum around the brand." }] },
      { type: "img", src: "/press/flowerboy/body-3.png" },
      { type: "h", text: "Future Vision" },
      { type: "p", spans: [{ text: "While Flowerboy is new to the THC beverage market, it’s not here for a quick hit." }] },
      { type: "p", spans: [{ text: "The vision is to build an enduring, category-defining brand:" }] },
      { type: "p", spans: [{ text: "“There’s a huge opportunity to build the go-to social THC brand, something that feels familiar, fun, and functional. It’s not just for stoners. It’s for anyone who wants to feel good without going overboard.” - Kyle" }] },
      { type: "p", spans: [{ text: "Flowerboy is betting that the next generation of social drinking will shift meaningfully away from alcohol toward functional, feel-good alternatives." }] },
      { type: "p", spans: [{ text: "It’s a bold wager, but one that could spark some seriously high rewards." }] },
    ],
    youtube: "https://youtu.be/V6uTFVXujOE",
    spotify: "https://open.spotify.com/show/7dLSJEJWuN0PQOX6bOddUz",
  },
  {
    slug: "flings",
    sourceUrl: "https://www.paperboyventures.com/blog/seatopia-3nz2p-mh9gw",
    title: "Flings lands $2.3m",
    date: "2025-04-25",
    author: "Kyle Fitzpatrick",
    excerpt: "The BFY toaster pastry brand closes its seed round to fuel US retail expansion following a successful pilot at Target.",
    heroImage: "/press/flings/hero.png",
    blocks: [
      { type: "img", src: "/press/flings/body-1.png" },
      { type: "p", spans: [{ text: "Like Pop Tarts, but MAHA friendly." }] },
      { type: "h", text: "Deal Overview" },
      { type: "p", spans: [{ text: "$2.3m in equity funding led by a single, undisclosed investor and supported by existing angels already invested in the brand." }] },
      { type: "p", spans: [{ text: "No institutional capital is reportedly involved and valuation was not disclosed." }] },
      { type: "p", spans: [{ text: "Though this is Flings’ first publicly reported raise it’s likely pre-seed funding was raised to get the operation off the ground in 2022." }] },
      { type: "p", spans: [{ text: "The goal?" }] },
      { type: "p", spans: [{ text: "Do for toaster pastries what " }, { text: "Goodles", href: "https://www.foodbusinessnews.net/articles/24663-goodles-gets-oodles-of-funding" }, { text: " has done for mac & cheese…" }] },
      { type: "h", text: "Why Flings is Fundable" },
      { type: "p", spans: [{ text: "1 / Proven CPG founders" }] },
      { type: "p", spans: [{ text: "Dino Vassilou", href: "https://www.linkedin.com/in/flings/" }, { text: " and " }, { text: "Ben Outmesguine", href: "https://www.linkedin.com/in/benjamin-outmezguine-b6a183aa/" }, { text: " are childhood friends and second-time CPG founders who previously built and ran CoolWhey Ice Cream, North America’s first protein-centric ice-cream brand." }] },
      { type: "p", spans: [{ text: "They launched CoolWhey in 2014 at ages 19 & 20 and ran the brand until exit in 2022, ultimately finding success in Canada as the fourth top-selling ice cream pint brand." }] },
      { type: "p", spans: [{ text: "Dino and Ben are now taking their learnings and capital earned from Coolwhey to Flings." }] },
      { type: "p", spans: [{ text: "Repeat CPG founders = fast-track to securing capital." }] },
      { type: "p", spans: [{ text: "2 / On-trend products" }] },
      { type: "p", spans: [{ text: "Low sugar (4g). High protein (10g). Low carb (9g). High fiber (10g)." }] },
      { type: "p", spans: [{ text: "Decadent flavors like Strawberry, Hot Chocolate, and Blueberry." }] },
      { type: "p", spans: [{ text: "Well-positioned to build the permissible indulgence brand of the breakfast category." }] },
      { type: "p", spans: [{ text: "Flings reformulated their pastries last year to further enhance nutritionals and improve taste / texture." }] },
      { type: "p", spans: [{ text: "In = honey, coconut oil Out = sugar alcohols, seed oils" }] },
      { type: "p", spans: [{ text: "Squarely on trend with what today’s consumer is looking for." }] },
      { type: "p", spans: [{ text: "3 / Mass-market potential" }] },
      { type: "p", spans: [{ text: "Pop-Tarts alone sell +$1b worth of pastries (US) each year and even has its own college football " }, { text: "bowl game", href: "https://poptartsbowl.com/" }, { text: "." }] },
      { type: "p", spans: [{ text: "Add in the growing BFY bakery sub-segment championed by nearly half (" }, { text: "46%", href: "https://www.glanbianutritionals.com/en/nutri-knowledge-center/insights/trends-bakery" }, { text: ") of US adults actively reducing sugar intake and the market is enormous." }] },
      { type: "p", spans: [{ text: "Flings has found early success in Target, driving strong velocities in a 500 store test scattered throughout the US." }] },
      { type: "p", spans: [{ text: "Expansion to 1,500 Target locations is coming by September with additional plans to grow with a few other strategic retailers." }] },
      { type: "p", spans: [{ text: "“Making Flings a household name in breakfast and snacking is the priority right now.” - Dino Vassilou per " }, { text: "NOSH", href: "https://www.nosh.com/news/2025/flings-nets-2-3m-seed-round" }, { text: "." }] },
    ],
  },
  {
    slug: "waku",
    sourceUrl: "https://www.paperboyventures.com/blog/seatopia-3nz2p",
    title: "Waku",
    tag: "DEALS · Ep. 21",
    date: "2025-04-21",
    author: "Kyle Fitzpatrick",
    excerpt: "Prebiotic teas with powerful herbs and vibrant flavors.",
    heroImage: "/press/waku/hero.png",
    blocks: [
      { type: "h", text: "A chat with Juan Giraldo, Cof & CEO of Waku Tea" },
      { type: "img", src: "/press/waku/body-1.png" },
      { type: "p", spans: [{ text: "Catch the interview on " }, { text: "Youtube", href: "https://youtu.be/r6QmR8uqs7I?si=x5cm5_ODRrXm46CG" }, { text: " or " }, { text: "Spotify", href: "https://open.spotify.com/episode/6CPZoCyfxI8eiuXT7zbiko?si=34375bc410204af7" }, { text: ". Subscribe to " }, { text: "DEALS here", href: "/deals" }, { text: "." }] },
      { type: "h", text: "What Stands Out" },
      { type: "p", spans: [{ text: "A refreshing approach to RTD tea…" }] },
      { type: "p", spans: [{ text: "Waku makes teas with vibrant flavors by blending powerful herbs with fruit juice to deliver gut-friendly brews that actually taste good." }] },
      { type: "p", spans: [{ text: "Inspired by horchata lojana, a centuries-old Ecuadorian tea brewed for its medicinal qualities, childhood friends and brand founders " }, { text: "Juan", href: "https://www.linkedin.com/in/juanjgiraldo/" }, { text: " Giraldo & " }, { text: "Nico", href: "https://www.linkedin.com/in/nico-estrella/" }, { text: " Estrella created Waku to bring taste of their culture with the masses." }] },
      { type: "p", spans: [{ text: "“Waku means ‘together’ in Quechua. It’s a reflection of how we work with farmers back home and what grounds everything we do.” - Juan" }] },
      { type: "h", text: "The Problem with RTD Tea" },
      { type: "p", spans: [{ text: "The $9b (US) ready-to-drink tea market has long been dominated by high-sugar, legacy brands like Arizona, Pure Leaf, and Gold Peak — many of which contain over 50g of sugar and 200+ calories per bottle." }] },
      { type: "p", spans: [{ text: "While many of those consumers will always stick with the old guard, a growing subset of more health-conscious humans are looking for alternatives." }] },
      { type: "p", spans: [{ text: "\"The leading teas out there? Many have 200% of your suggested daily sugar intake,\" Juan says. \"That’s just not what the new generation is looking for.\" - Juan" }] },
      { type: "p", spans: [{ text: "But a BFY wave is brewing, and if tea follows anywhere near a similar trajectory to soda (👋 " }, { text: "Poppi", href: "https://www.forbes.com/sites/claraludmir/2025/03/17/pepsi-co-buys-poppi-/" }, { text: ", " }, { text: "Olipop", href: "https://www.bloomberg.com/news/articles/2025-02-12/olipop-valued-at-1-85-billion-in-50-million-funding-round?embedded-checkout=true" }, { text: "), it won’t be long until multiple breakout winners emerge…" }] },
      { type: "img", src: "/press/waku/body-2.png" },
      { type: "p", spans: [{ text: "Chuquiribamba Farm in Loja, Ecuador" }] },
      { type: "h", text: "How Waku is Flipping the Script" },
      { type: "p", spans: [{ text: "It all starts with the product." }] },
      { type: "p", spans: [{ text: "Waku teas are made with a blend of functional herbs like lemongrass, chamomile, and white basil — all to support gut health and fight inflammation in the body." }] },
      { type: "p", spans: [{ text: "The fruit-forward lineup:" }] },
      { type: "p", spans: [{ text: "🍑 Peach🍍 Pineapple🍇 Raspberry🥭 Passion Fruit" }] },
      { type: "p", spans: [{ text: "5g of prebiotic fiber. 3-4g of sugar. 30 calories. Caffeine free and in a shelf-stable format." }] },
      { type: "p", spans: [{ text: "Well positioned for the more mindful consumer." }] },
      { type: "p", spans: [{ text: "First launched in 2019, Waku has experimented with numerous packaging formats and designs before finding the ultimate combo recently:" }] },
      { type: "p", spans: [{ text: "“The rebrand in 2024 was a turning point. The team moved from plastic to aluminum, dialed in their design hierarchy, and leaned into vibrant visual cues that made the product scream from the shelf. The result? Velocities surged overnight.” - Juan" }] },
      { type: "img", src: "/press/waku/body-3.jpg" },
      { type: "p", spans: [{ text: "Waku product lineup. " }, { text: "Try", href: "https://livewaku.com/" }, { text: " for 20% off code ‘PAPERBOY20’." }] },
      { type: "h", text: "The Road to $100 Million" },
      { type: "p", spans: [{ text: "While the brand is taking a disciplined approach to ‘dominate the Northeast’ in the short-term, larger aspirations loom on the horizon." }] },
      { type: "p", spans: [{ text: "The goal? Double revenue each year until hitting $100m by 2031." }] },
      { type: "p", spans: [{ text: "It’s a tall task but given the product/team quality and potential for category expansion the potential is significant." }] },
      { type: "p", spans: [{ text: "\"We’re just getting started,\" Juan says. \"We’ve never had a business this good. The product is working, the brand is resonating, and we’re obsessed with building this the right way.\"" }] },
      { type: "p", spans: [{ text: "Waku may be early in its journey, but it’s playing a long game — one steeped in flavor, function, and impact." }] },
    ],
    youtube: "https://youtu.be/r6QmR8uqs7I?si=x5cm5_ODRrXm46CG",
    spotify: "https://open.spotify.com/episode/6CPZoCyfxI8eiuXT7zbiko?si=34375bc410204af7",
  },
  {
    slug: "culture-pop",
    sourceUrl: "https://www.paperboyventures.com/blog/seatopia-3nz2p-mh9gw-m96lk",
    title: "Culture Pop lands $15m",
    date: "2025-04-17",
    author: "Kyle Fitzpatrick",
    excerpt: "The ‘modern soda’ brand closes fresh funding to scale marketing & distribution efforts across the US.",
    heroImage: "/press/culture-pop/hero.png",
    blocks: [
      { type: "img", src: "/press/culture-pop/body-1.png" },
      { type: "p", spans: [{ text: "“If Soda Grew on Trees” - one of the best taglines in the game." }] },
      { type: "h", text: "Deal Background" },
      { type: "p", spans: [{ text: "The $15m deal was led by Enlightened Hospitality Group (" }, { text: "EHI", href: "https://ehi.fund/" }, { text: ") and brings total brand funding to +$40m since founding in 2020." }] },
      { type: "p", spans: [{ text: "$12m is still available in the round with all signs pointing towards that allocation filling shortly." }] },
      { type: "p", spans: [{ text: "Culture Pop’s funding roadmap thus far: May 2020 - $215k (seed 1.0)Sep 2020 - $1.1m (debt)May 2021 - $3.5m (seed 2.0)Feb 2024 - $21m (growth)" }] },
      { type: "p", spans: [{ text: "Other brand investors include " }, { text: "Howard Schultz", href: "https://en.wikipedia.org/wiki/Howard_Schultz" }, { text: " and TF Ventures, the investment firm led by " }, { text: "Tom First", href: "https://www.linkedin.com/in/tom-first-532ab55/" }, { text: " — the definition of smart money." }] },
      { type: "p", spans: [{ text: "Culture Pop’s Goal?" }] },
      { type: "p", spans: [{ text: "Bring “soda that’s actually good for you” to the masses." }] },
      { type: "p", spans: [{ text: "And if they can pull it off, CP might just be looking at a multi-billion $ outcome…" }] },
      { type: "h", text: "Why Culture Pop is Fundable" },
      { type: "p", spans: [{ text: "1 / The Modern Soda Market" }] },
      { type: "p", spans: [{ text: "The latest billion $ product category, " }, { text: "modern soda", href: "https://www.linkedin.com/posts/kylefitzpat_cpg-soda-walmart-activity-7260292289397231617-tDG4/" }, { text: " is home to Poppi & Olipop as well as many other startups looking to earn a slice of the $41b (US) soda market." }] },
      { type: "p", spans: [{ text: "A look at how retail sales of modern soda have grown over the past four years (per " }, { text: "Numerator", href: "https://www.linkedin.com/posts/kylefitzpat_cpg-beverage-soda-activity-7155568145942941697-eDYW/" }, { text: "):" }] },
      { type: "p", spans: [{ text: "2021 - $71m2022 - $161m2023 - $486m2024 - $1b" }] },
      { type: "p", spans: [{ text: "It’s a safe bet to say the growth here is just getting started as modern soda makes up roughly 2% of total CSD volume." }] },
      { type: "p", spans: [{ text: "Could this grow to 5, 10, or even 20% in the coming years? It’s not out of the question." }] },
      { type: "p", spans: [{ text: "2 / Product Quality and Positioning" }] },
      { type: "p", spans: [{ text: "Culture Pop sits in a valuable strategic position vs. modern soda from a product standpoint." }] },
      { type: "p", spans: [{ text: "The brand uses organic fruit juice, spices, and live probiotics to power it’s beverages." }] },
      { type: "p", spans: [{ text: "No high intensity sweeteners or ‘natural flavors’ whatsoever." }] },
      { type: "p", spans: [{ text: "Conversely, most major competitors in the space rely heavily on flavor extracts, stevia, and natural flavors to simulate fruit taste rather than using real fruit." }] },
      { type: "p", spans: [{ text: "This difference allows Culture Pop to boast the cleanest label in the category, a critical advantage in landing lucrative, health-conscious consumers." }] },
      { type: "p", spans: [{ text: "3 / Leadership Excellence" }] },
      { type: "p", spans: [{ text: "Tom First (founder, CEO) is a legend in the beverage industry best known as co-founder of Nantucket Nectars, a juice brand launched in the 1980s that was eventually acquired by Cadbury in 2002." }] },
      { type: "p", spans: [{ text: "Since that sale, Tom has remained active in the food / bev space as an investor and advisor with First Beverage Ventures, Castanea Partners, and TF Ventures." }] },
      { type: "p", spans: [{ text: "Culture Pop is his latest entrepreneurial ventures and he’s assembled an all-star team of operators including " }, { text: "Ben Tuttman", href: "https://www.linkedin.com/in/ben-tuttman/" }, { text: ", " }, { text: "Andrew Merle", href: "https://www.linkedin.com/in/drewmerle/" }, { text: ", and " }, { text: "Brendan Burns", href: "https://www.linkedin.com/in/brendan-burns-b97781101/" }, { text: " to build the future of the brand." }] },
    ],
  },
  {
    slug: "elavi",
    sourceUrl: "https://www.paperboyventures.com/blog/seatopia-tj9ws",
    title: "Elavi",
    tag: "DEALS · Ep. 20",
    date: "2025-04-11",
    author: "Kyle Fitzpatrick",
    excerpt: "Brownies that function like protein bars, but taste like desserts.",
    heroImage: "/press/elavi/hero.png",
    blocks: [
      { type: "h", text: "A chat with Michelle Razavi, Cof & CEO of Elavi" },
      { type: "img", src: "/press/elavi/body-1.png" },
      { type: "p", spans: [{ text: "Catch the full interview on " }, { text: "Youtube", href: "https://youtu.be/pvUhsHvHRXY?si=Qc-Pfy1RzmMWmr6-" }, { text: " or " }, { text: "Spotify", href: "https://open.spotify.com/episode/42cSlkGCewZrKoSeI4QzmD?si=37c2b492e2f747af" }, { text: ". Subscribe to " }, { text: "DEALS here", href: "/deals" }, { text: "." }] },
      { type: "h", text: "What Stands Out" },
      { type: "p", spans: [{ text: "Brownies that function like protein bars, but taste like desserts." }] },
      { type: "p", spans: [{ text: "Elavi is redefining permissible indulgence with a line of appetizing products that deliver sound nutrition without sacrificing flavor." }] },
      { type: "p", spans: [{ text: "\"We wanted to solve for the sweet craving without the sugar crash,\" Michelle says. \"The brownie lets you have both — pleasure and nutrition in one bite.\"" }] },
      { type: "p", spans: [{ text: "Simply stated. Incredibly challenging to execute." }] },
      { type: "h", text: "The Gap in Protein Snacks Today" },
      { type: "p", spans: [{ text: "Though the $8b protein snack market is booming many products still miss the mark." }] },
      { type: "p", spans: [{ text: "First, many BFY snacks are anything but, often packed with sugar, artificial ingredients, and cheap fillers." }] },
      { type: "p", spans: [{ text: "Even worse, they often lack in taste, forcing consumers to choose between flavor and nutrition." }] },
      { type: "p", spans: [{ text: "Second, the category’s branding still heavily skews masculine." }] },
      { type: "p", spans: [{ text: "Traditional protein bars and snacks often lean on “bodybuilder” aesthetics with hyper-agro imagery and flavor profiles that don’t connect with the health-conscious, female demographic." }] },
      { type: "p", spans: [{ text: "Elavi was created specifically to fill these voids." }] },
      { type: "p", spans: [{ text: "\"We saw that protein snacks were mostly made for men — bodybuilder branding, chalky taste — and we wanted something delicious, functional, and actually appealing to women.\" - Michelle" }] },
      { type: "img", src: "/press/elavi/body-2.jpeg" },
      { type: "p", spans: [{ text: "Elavi brownies and cashew butter spreads. " }, { text: "Try", href: "https://elavi.co/" }, { text: " for 10% off with code 'PAPERBOY20’" }] },
      { type: "h", text: "How Elavi is Raising the Bar" },
      { type: "p", spans: [{ text: "The brand has refined its signature offerings after years of R&D alongside a world-class food scientist:" }] },
      { type: "p", spans: [{ text: "🍫 High-protein Brownies🥜 Cashew Butter Dessert Spreads" }] },
      { type: "p", spans: [{ text: "Naturally sweetened with dates and made with plant-based protein, Elavi formulas emphasize simplicity and functionality." }] },
      { type: "p", spans: [{ text: "Cofounders Michelle & Nikki are experienced operators with complementary expertise in marketing and finance. As active fitness instructors, they bring a unique perspective to the business and stay connected to their core audience." }] },
      { type: "p", spans: [{ text: "The brand name ‘Elavi’ merges their last names with a nod to the word ‘elevate’, which is exactly what the business is currently doing…" }] },
      { type: "img", src: "/press/elavi/body-3.jpg" },
      { type: "p", spans: [{ text: "Nikki (left) and Michelle (right) enjoying their Costco launch." }] },
      { type: "h", text: "What’s Next for Elavi" },
      { type: "p", spans: [{ text: "2024 was a breakout year for Elavi, delivering strong revenue by way of execution with Costco and Amazon." }] },
      { type: "p", spans: [{ text: "Costco alone ordered +1 million brownies since launching in May 2024." }] },
      { type: "p", spans: [{ text: "Whole Foods comes onboard this Summer with distribution expanding to Southern California." }] },
      { type: "p", spans: [{ text: "The shelf-stable and unmeltable nature of Elavi’s products allow for penetration into nearly all channels of trade, avoiding cold-chain logistics. True mass market potential." }] },
      { type: "p", spans: [{ text: "\"We want to own the category of permissible indulgence,\" Michelle says. \"And that means staying laser focused on the consumer, solving their needs, and doing it better than anyone else.\"" }] },
      { type: "p", spans: [{ text: "With a team built for both hustle and discipline, a loyal customer base, and a product that truly delivers, Elavi is poised to lead the next generation of snack innovation — one brownie at a time." }] },
    ],
    youtube: "https://youtu.be/pvUhsHvHRXY?si=Qc-Pfy1RzmMWmr6-",
    spotify: "https://open.spotify.com/episode/42cSlkGCewZrKoSeI4QzmD?si=37c2b492e2f747af",
  },
  {
    slug: "seatopia",
    sourceUrl: "https://www.paperboyventures.com/blog/seatopia",
    title: "Seatopia",
    tag: "DEALS · Ep. 19",
    date: "2025-04-04",
    author: "Kyle Fitzpatrick",
    excerpt: "Building a fully-traceable DTC supply chain with sushi-grade seafood that’s both sustainably farmed and lab-tested for contaminants.",
    heroImage: "/press/seatopia/hero.png",
    blocks: [
      { type: "h", text: "A chat with James Arthur Smith, Cof & CEO of Seatopia" },
      { type: "img", src: "/press/seatopia/body-1.png" },
      { type: "p", spans: [{ text: "Catch the interview on " }, { text: "Youtube", href: "https://youtu.be/sxi1RjO0cgk?si=YbFlGxnWqW4TXxpx" }, { text: " or " }, { text: "Spotify", href: "https://open.spotify.com/episode/2AM8jG7DRfw65EFsGi01Vo?si=219cac3e268c469a" }, { text: ". Subscribe to " }, { text: "DEALS here", href: "/deals" }, { text: "." }] },
      { type: "h", text: "What Stands Out" },
      { type: "p", spans: [{ text: "The first and only seafood brand building a fully traceable, DTC supply chain with sushi-grade seafood that’s both sustainably farmed and lab-tested for contaminants." }] },
      { type: "p", spans: [{ text: "Seatopia is in a quality class of its own and tests each batch of seafood for mercury, microplastics, and nutrient density." }] },
      { type: "p", spans: [{ text: "Their commitment to regenerative aquaculture not only delivers healthier seafood but also sets a new sustainability standard that actively restores ocean ecosystems." }] },
      { type: "p", spans: [{ text: "\"The vision is to create a low-risk model for farms to transition their feed practices to things that are healthier for the planet and healthier for humans. As we scale, we’re scaling that impact. I believe we can change the seafood industry—change the way food is produced around the world.\" - James" }] },
      { type: "h", text: "The Problem with Seafood Sourcing" },
      { type: "p", spans: [{ text: "Our traditional methods of sourcing seafood have reached a breaking point." }] },
      { type: "p", spans: [{ text: "Wild-caught fish populations are under immense pressure due to decades of relentless overfishing, driven by global seafood demand that’s outpaced natural replenishment rates. Many of the world’s fisheries are now pushed beyond their sustainable limits." }] },
      { type: "p", spans: [{ text: "According to the Food and Agriculture Organization, approximately 85% of global fish stocks are either fully exploited or significantly depleted." }] },
      { type: "p", spans: [{ text: "The fish we do catch often cary unwanted contaminants from polluted oceans like mercury and microplastics." }] },
      { type: "p", spans: [{ text: "Farm-raised fish have long suffered from poor practices — crowded pens and artificial diets packed with GMOs, cheap oils, and antibiotics." }] },
      { type: "p", spans: [{ text: "The status quo can’t continue much longer." }] },
      { type: "p", spans: [{ text: "\"Jacques Cousteau famously said, 'The mark of civilization is the transition from hunters and gatherers to farmers.' And we need to learn how to do the same thing in the ocean, to evolve from extraction to cultivation and farming. That's what we're trying to do with Seatopia.” - James" }] },
      { type: "img", src: "/press/seatopia/body-2.png" },
      { type: "p", spans: [{ text: "Seatopia scallops raised in hanging lanterns in Sechura Bay, Peru" }] },
      { type: "h", text: "The Seatopia Solution" },
      { type: "p", spans: [{ text: "Seatopia is flipping the old seafood supply chain on its head with a model focused on delivering the cleanest seafood on the planet to consumers with no middlemen." }] },
      { type: "p", spans: [{ text: "Butcherbox, but for seafood." }] },
      { type: "p", spans: [{ text: "How it works:" }] },
      { type: "p", spans: [{ text: "First, Seatopia finds and partners with the top aquaculture farms around the globe, vetting fish diets, environment, and sustainability." }] },
      { type: "p", spans: [{ text: "Seatopia meticulously evaluates farm practices, prioritizing those that use innovative feeds like microalgae and insect proteins." }] },
      { type: "p", spans: [{ text: "Next, seafood is harvested and immediately blast-frozen on-site to preserve peak freshness. Lab tests happen concurrently to confirm quality." }] },
      { type: "p", spans: [{ text: "Lab tests happen concurrently to confirm quality. Utilizing advanced nitrogen and blast-freezing tech, Seatopia locks in optimal flavor, texture and nutrition, while lab testing verifies omega-3 levels and confirms zero detectable mercury, microplastics, and contaminants." }] },
      { type: "p", spans: [{ text: "Last, approved seafood is shipped to Seatopia warehouses for purchase by the end consumer via subscription or a-la-carte." }] },
      { type: "p", spans: [{ text: "Each shipment is carefully packed with dry ice and temperature sensors to ensure quality is maintained door-to-door, providing consumers with convenient, safe, and sustainably-sourced seafood experiences." }] },
      { type: "p", spans: [{ text: "On the menu:" }] },
      { type: "p", spans: [{ text: "🍣 Salmon I " }, { text: "Ora King", href: "https://seatopia.fish/pages/ora-king-salmon-new-zealand" }, { text: ", New Zealand 🐠 Branzino I " }, { text: "Esteros Lubimar", href: "https://seatopia.fish/pages/esteros-lubimar" }, { text: ", Spain 🐟 Steelhead I " }, { text: "Hudson Valley Trout", href: "https://seatopia.fish/pages/usa-steelhead-trout#" }, { text: ", New York🦪 Scallops I " }, { text: "Sechura Bay", href: "https://seatopia.fish/pages/peruvian-scallops-seacorp" }, { text: ", Peru" }] },
      { type: "img", src: "/press/seatopia/body-3.jpg" },
      { type: "p", spans: [{ text: "Fish & Shellfish Variety Box. " }, { text: "15% off ", href: "https://seatopia.fish/pages/choose-box" }, { text: "with code ‘PAPERBOY’" }] },
      { type: "h", text: "Aquaculture 3.0" },
      { type: "p", spans: [{ text: "Seatopia’s vision extends beyond simply selling fish; it’s more about transforming an antiquated industry and restoring balance to our oceans." }] },
      { type: "p", spans: [{ text: "This is aquaculture 3.0. A model that prioritizes species-appropriate diets, cleaner environments, and full traceability." }] },
      { type: "p", spans: [{ text: "It’s an ambitious mission, but the timing is right. With consumers increasingly prioritizing health and sustainability, and wild fisheries in decline, Seatopia offers a hopeful path forward." }] },
      { type: "p", spans: [{ text: "If James and his team succeed, the future of seafood will be one where we can enjoy delicious, nutrient-rich fish without worrying about mercury or wiping out species – a future where our oceans thrive and dinner plates are full of responsibly raised bounty." }] },
      { type: "p", spans: [{ text: "\"Aquaculture 3.0 is not just sustainable but scalable and nutrient-rich. This evolution towards regenerative practices comes down to diet, farming practices, and site location, all directly benefiting ocean health.\" - James" }] },
    ],
    youtube: "https://youtu.be/sxi1RjO0cgk?si=YbFlGxnWqW4TXxpx",
    spotify: "https://open.spotify.com/episode/2AM8jG7DRfw65EFsGi01Vo?si=219cac3e268c469a",
  },
];
